spring:
  application:
    name: Api-Gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka